Feature Selection:
- name: Logistic Regression
  params:
    C: 1000.0
    penalty: l1
    tol: 1.0e-06

Classifier:
- name: Logistic Regression
  params:
    C: 10.0
    penalty: l2
    tol: 1.0e-01
- name: MultinomialNB
  params:
    alpha: 0.001
    fit_prior: true
- name: kNN
  params:
    algorithm: auto
- name: Perceptron
  params:
    alpha: 0.001
    n_iter: 3
- name: SVM
  params:
    C: 1.0
    gamma: 100.0
    kernel: linear
- name: RBF SVM
  params:
    C: 1000.0
    gamma: 1.0e-05
    kernel: rbf
- name: LinearSVC
  params:
    C: 1.0
    penalty: l1
    tol: 0.1
- name: Extra Trees
  params:
    max_features: 0.7
    min_samples_leaf: 20
    n_estimators: 500
- name: Random Forest
  params:
    max_features: 0.6
    min_samples_leaf: 1
    n_estimators: 400
    class_weight: balanced
- name: GB LinearSVC
  params:
    learning_rate: 0.6
    loss: exponential
    max_features: 0.6
    min_samples_leaf: 20
    n_estimators: 400
    subsample: 0.7
    warm_start: false

- name: RBF SVM 102-2
  params:
    C: 100.0
    gamma: 1.0e-02
    kernel: rbf
- name: RBF SVM 103-2
  params:
    C: 1000.0
    gamma: 1.0e-02
    kernel: rbf
- name: RBF SVM 102-3
  params:
    C: 100.0
    gamma: 1.0e-03
    kernel: rbf
- name: RBF SVM 103-3
  params:
    C: 1000.0
    gamma: 1.0e-03
    kernel: rbf
- name: Random Forest for BinOrig
  params:
    max_features: 1.0
    min_samples_leaf: 1
    n_estimators: 1000
- name: Random Forest for TfidfOrig
  params:
    max_depth: 80
    max_features: 1.0
    min_samples_leaf: 1
    n_estimators: 400
    class_weight: balanced
- name: Random Forest for FiltXU
  params:
    max_features: 0.7
    min_samples_leaf: 1
    n_estimators: 1000
    class_weight: balanced
- name: Random Forest for DtFiltX
  params:
    max_depth: 30
    max_features: 0.9
    min_samples_leaf: 1
    n_estimators: 600
    class_weight: balanced
- name: Random Forest for UDtFiltX
  params:
    max_depth: 30
    max_features: 0.6
    min_samples_leaf: 1
    n_estimators: 1000
    class_weight: balanced
- name: Random Forest for ExpDtFiltX
  params:
    max_depth: 30
    max_features: 0.5
    min_samples_leaf: 1
    n_estimators: 1000
    class_weight: balanced
- name: Random Forest for ExpUDtFiltX
  params:
    max_features: 0.7
    min_samples_leaf: 1
    n_estimators: 200
    class_weight: balanced
- name: Random Forest for GssFiltX
  params:
    max_features: 0.8
    min_samples_leaf: 1
    n_estimators: 800
    class_weight: balanced
- name: Random Forest for UGssFiltX
  params:
    max_features: 0.5
    min_samples_leaf: 1
    n_estimators: 800
    class_weight: balanced
- name: Random Forest for ExpGssFiltX
  params:
    class_weight: balanced
- name: Random Forest for ExpUGssFiltX
  params:
    max_depth: 30
    max_features: 0.5
    min_samples_leaf: 1
    n_estimators: 200
    class_weight: balanced
- name: Random Forest for NglFiltX
  params:
    max_depth: 30
    max_features: 1.0
    min_samples_leaf: 1
    n_estimators: 200
    class_weight: balanced
- name: Random Forest for UNglFiltX
  params:
    max_depth: 40
    max_features: 0.8
    min_samples_leaf: 1
    n_estimators: 600
    class_weight: balanced
- name: Random Forest for ExpNglFiltX
  params:
    max_depth: 20
    max_features: 1.0
    min_samples_leaf: 1
    n_estimators: 200
    class_weight: balanced
- name: Random Forest for ExpUNglFiltX
  params:
    max_features: 0.7
    min_samples_leaf: 1
    n_estimators: 200
    class_weight: balanced
- name: Random Forest for Filt0
  params:
    max_features: sqrt
    min_samples_leaf: 10
    n_estimators: 400
    class_weight: balanced
- name: Random Forest for Filt1
  params:
    max_features: 0.5
    min_samples_leaf: 1
    n_estimators: 600
- name: Random Forest for Filt2
  params:
    max_features: 0.6
    min_samples_leaf: 1
    n_estimators: 200
    class_weight: balanced
- name: Random Forest for Filt3
  params:
    max_features: 0.5
    min_samples_leaf: 10
    n_estimators: 100
    class_weight: balanced
- name: Random Forest for Filt4
  params:
    max_features: 0.5
    min_samples_leaf: 10
    n_estimators: 800
- name: Random Forest for Filt5
  params:
    max_features: 0.9
    min_samples_leaf: 10
    n_estimators: 400
- name: Random Forest for Filt6
  params:
    max_features: 0.6
    min_samples_leaf: 1
    n_estimators: 100
- name: Random Forest for Filt7
  params:
    max_features: 0.6
    min_samples_leaf: 10
    n_estimators: 100
- name: Random Forest for Filt8
  params:
    max_features: 0.9
    min_samples_leaf: 1
    n_estimators: 100
    class_weight: balanced
- name: Random Forest for Filt9
  params:
    max_features: 0.6
    min_samples_leaf: 1
    n_estimators: 600
- name: Random Forest for FiltExp0
  params:
    max_features: sqrt
    min_samples_leaf: 10
    n_estimators: 400
    class_weight: balanced
- name: Random Forest for FiltExp1
  params:
    max_features: 0.5
    min_samples_leaf: 1
    n_estimators: 600
- name: Random Forest for FiltExp2
  params:
    max_features: 0.6
    min_samples_leaf: 1
    n_estimators: 200
    class_weight: balanced
- name: Random Forest for FiltExp3
  params:
    max_features: 0.5
    min_samples_leaf: 10
    n_estimators: 100
    class_weight: balanced
- name: Random Forest for FiltExp4
  params:
    max_features: sqrt
    min_samples_leaf: 10
    n_estimators: 600
    class_weight: balanced
- name: Random Forest for FiltExp5
  params:
    max_features: 0.9
    min_samples_leaf: 10
    n_estimators: 400
- name: Random Forest for FiltExp6
  params:
    max_features: 0.6
    min_samples_leaf: 1
    n_estimators: 100
- name: Random Forest for FiltExp7
  params:
    max_features: 0.6
    min_samples_leaf: 10
    n_estimators: 100
    class_weight: balanced
- name: Random Forest for FiltExp8
  params:
    max_features: 0.9
    min_samples_leaf: 1
    n_estimators: 100
    class_weight: balanced
- name: Random Forest for FiltExp9
  params:
    max_features: 0.6
    min_samples_leaf: 600
    n_estimators: 1